const KeysMap = {
  Delete: "del",
  Backspace: "backspace",
  Insert: "insert",
  NumLock: "numlock",
  CapsLock: "capslock",
  Pause: "pause",
  ContextMenu: "contextmenu",
  ScrollLock: "scrolllock",
  BrowserHome: "browserhome",
  MediaSelect: "mediaselect",
  Shift: "shift",
  Control: "ctrl",
  Alt: "alt",
  AltGraph: "altgraph",
  Super: "meta",
  Cmd: "meta",
  Meta: "meta",
  ArrowUp: "arrowup",
  ArrowDown: "arrowdown",
  ArrowLeft: "arrowleft",
  ArrowRight: "arrowright",
  Enter: "enter",
  Escape: "esc",
  Tab: "tab",
  Space: "space",
  " ": "space",
  PageUp: "pageup",
  PageDown: "pagedown",
  Home: "home",
  End: "end",
};

export default KeysMap;
